name: gh-pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - ci

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
 
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          cache-dependency-path: frontend/package-lock.json
          node-version: 16
          cache: 'npm'

      - name: Build with Maven
        run: mvn --batch-mode package

      - run: |
          cd frontend && sed -i "`wc -l < vue.config.js`i\\publicPath: \"/PlayerList/\",\\" vue.config.js
      - run: cd frontend && npm ci
      - run: cd frontend && npm run build
      - run: touch frontend/dist/.nojekyll
      
      - run: |
          cp target/playerlist-1.0-SNAPSHOT.jar frontend/dist/playerlist.jar
          echo '# This version is only to be used with Github Pages, because it only works on `/PlayerList` as path.' > frontend/dist/README.md

      - name: Deploy to pages
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: ./frontend/dist
          clean: true
          single-commit: true
          git-config-name: 'github-actions'
          git-config-email: '<>'
