name: gh-pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - ci

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          cache-dependency-path: frontend/package-lock.json
          node-version: 16
          cache: 'npm'

      - run: |
          cd frontend && sed -i "`wc -l < vue.config.js`i\\publicPath: \"/PlayerList/\",\\" vue.config.js 
      - run: cd frontend && npm ci
      - run: cd frontend && npm run build
          
      - name: deploy-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          
