name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - ci

jobs:
  bungee:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode package
      - uses: actions/upload-artifact@v2
        with:
          name: PlayerList.jar
          path: target/playerlist-1.0-SNAPSHOT.jar

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          cache-dependency-path: frontend/package-lock.json
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: frontend/dist
